### PR TITLE
Add option to reset field on hide

### PR DESCRIPTION
**Pull request by Tropicalista**

### CODE REVIEW

**Comment by bomsn** [comment]
Hello, 
When you set the value like this `field.value = '';` it may effect checkbox/radio and select fields in the wrong way.

**Comment by Tropicalista** [comment]
About radio/checkbox you are right. But select? should work.

What if we add `disabled` attribute?

**Comment by bomsn** [comment]
Good point, I'm going to push an update soon to handle hidden field ( empty value + disable the field )

**Comment by Tropicalista** [comment]
I think it's better to simply disable the field, so the user will have a copy of previously inserted data if he chenge his mind.

**Comment by bomsn** [comment]
Hello, I made the update, please check the Readme for instructions, you can decide whether you want to reset or disable the fields.

**Comment by Tropicalista** [comment]
Many thanks!

**Pull request closed without merging**
